export {
  createProgram,
  findProgramByCode,
  findProgramById,
  listPrograms,
  programTargetRef,
  type CreateProgramInput,
  type ProgramRow,
} from "./program-repository.ts";

export {
  ProgramNotEnrolledError,
  assertProgramAccess,
  listAccessibleProgramsForUser,
  setPrimaryProgram,
  syncProgramEnrollments,
  type EnrollmentRow,
} from "./enrollment-service.ts";

export { buildHomeViewModel, type HomeViewModel } from "./home-view-service.ts";

export {
  CircularPrerequisiteError,
  ModuleAlreadyArchivedError,
  ModuleNotFoundError,
  ProgramVersionLockedError,
  ProgramVersionNotFoundError,
  ResourceVersionNotFoundError,
  ResourceVersionNotPublishedError,
  archiveModule,
  createModule,
  createProgramVersionDraft,
  createResource,
  createResourcePlacement,
  createResourceVersion,
  createRoadmapStage,
  createTrack,
  findCurrentPublishedProgramVersion,
  findPlacementDeliveryContext,
  findProgramVersionById,
  findResourceByCode,
  listModulesForProgramVersion,
  publishProgramVersion,
  publishResourceVersion,
  type CreateModuleInput,
  type CreateProgramVersionDraftInput,
  type CreateResourcePlacementInput,
  type CreateResourceVersionInput,
  type CreateRoadmapStageInput,
  type CreateTrackInput,
  type ModuleRow,
  type PlacementDeliveryContext,
  type ProgramVersionRow,
  type ResourcePlacementRow,
  type ResourceRow,
  type ResourceVersionRow,
  type RoadmapStageRow,
  type TrackRow,
} from "./curriculum-repository.ts";

export {
  getProgramCurriculum,
  type CurriculumAccessResult,
  type CurriculumModuleView,
  type ProgramCurriculumView,
} from "./curriculum-service.ts";

export {
  RecordingNotFoundError,
  createAsset,
  createDeliveryReference,
  createRecording,
  findAssetById,
  findDeliveryReferenceByTokenHash,
  findPrimaryAssetForResourceVersion,
  findRecordingByResourceVersionId,
  markRecordingFailed,
  markRecordingReady,
  type AssetRow,
  type CreateAssetInput,
  type CreateDeliveryReferenceInput,
  type CreateRecordingInput,
  type DeliveryReferenceRow,
  type RecordingRow,
} from "./asset-repository.ts";

export {
  requestAssetDelivery,
  resolveAssetDelivery,
  type AssetDeliveryRequestResult,
  type AssetDeliveryResolution,
} from "./delivery-service.ts";

export {
  createAttendanceCheckIn,
  createJoinReference,
  createLiveSession,
  createReminder,
  createScheduleItem,
  findAttendanceRecord,
  findJoinReferenceByTokenHash,
  findLiveSessionById,
  findScheduleItemById,
  linkRecordingToLiveSession,
  listRemindersForSession,
  recordAttendanceCheckOut,
  updateLiveSessionStatus,
  type AttendanceRow,
  type CreateLiveSessionInput,
  type CreateScheduleItemInput,
  type JoinReferenceRow,
  type LiveSessionRow,
  type ReminderRow,
  type ScheduleItemRow,
  type UpdateLiveSessionStatusInput,
} from "./schedule-repository.ts";

export {
  LiveSessionNotFoundError,
  ScheduleActionNotAuthorizedError,
  ScheduleReasonRequiredError,
  cancelLiveSession,
  checkInToLiveSession,
  checkOutOfLiveSession,
  linkRecording,
  rescheduleLiveSession,
  requestLiveSessionJoin,
  resolveLiveSessionJoin,
  scheduleReminder,
  type JoinRequestOutcome,
  type JoinResolution,
  type RescheduleResult,
} from "./schedule-service.ts";
